'use strict';
const KEY='mi-pausa-history-v1';
const app=document.querySelector('#app'),notice=document.querySelector('#notice');
const groups=[{name:'Con energía agradable',desc:'Energía alta · sensación agradable',cls:'warm',words:['Entusiasmo','Alegría','Motivación','Orgullo']},{name:'Con energía incómoda',desc:'Energía alta · sensación desagradable',cls:'rose',words:['Preocupación','Frustración','Enojo','Nervios']},{name:'Con poca energía e incomodidad',desc:'Energía baja · sensación desagradable',cls:'blue',words:['Tristeza','Desánimo','Soledad','Agotamiento']},{name:'Con calma agradable',desc:'Energía baja · sensación agradable',cls:'green',words:['Calma','Gratitud','Alivio','Serenidad']}];
let step=0,state={},saved=false,view='flow';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readHistory(){const raw=localStorage.getItem(KEY);if(raw===null)return [];const rows=JSON.parse(raw);if(!Array.isArray(rows)||rows.some(r=>!r||typeof r!=='object'||typeof r.id!=='string'||!Number.isFinite(Date.parse(r.date))))throw Error('invalid history');return rows;}
function options(list,value){return '<option value="">Elige si te ayuda…</option>'+list.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('');}
function render(focus=true){view='flow';notice.textContent='';const titles=['¿Cómo llegas a esta pausa?','¿Cómo te sientes ahora?','¿Qué podría estar influyendo?','¿Qué te ayudaría ahora?','¿Qué acción quieres elegir?','Esto es lo que reconoces hoy'];let body='';
if(step===0)body=`<p>Elige el momento que mejor describe tu pausa.</p><div class="choices">${['Al comenzar','Para continuar','Al cerrar'].map(x=>`<button class="choice" data-moment="${x}" aria-pressed="${state.moment===x}">${x}</button>`).join('')}</div>`;
if(step===1){body=`<p>Observa tu energía y qué tan agradable o desagradable se siente este momento. Ninguna zona es mejor que otra.</p><div class="choices">${groups.map((g,i)=>`<button class="choice ${g.cls}" data-group="${i}" aria-pressed="${state.group===i}"><strong>${g.name}</strong><small>${g.desc}</small></button>`).join('')}</div>`;if(Number.isInteger(state.group))body+=`<label for="emotion">¿Qué palabra se acerca a lo que sientes?</label><select id="emotion">${options([...groups[state.group].words,'Otra emoción','No lo tengo claro'],state.emotion)}</select>`;body+=`<label for="ownEmotion">Tu propia palabra (opcional)</label><input id="ownEmotion" type="text" maxlength="80" value="${esc(state.ownEmotion)}"><button class="secondary" id="unclear" style="margin-top:1rem">No lo tengo claro</button>`;}
if(step===2)body=`<p>${state.moment==='Al cerrar'?'¿Qué experiencia del día sigue contigo?':'¿Hay algo que te ayude a entender cómo te sientes?'} Puedes dejarlo en blanco.</p><label for="reason">Una posible razón (opcional)</label><select id="reason">${options(['Algo que ocurrió','Algo que espero','Descanso o energía','Una relación','Una tarea','Un logro','No sé todavía'],state.reason)}</select><label for="detail">Si quieres, cuéntatelo con tus palabras</label><textarea id="detail" maxlength="500">${esc(state.detail)}</textarea>`;
if(step===3)body=`<p>Una misma emoción puede acompañarse de necesidades distintas. Tú eliges lo que tiene sentido para ti.</p><label for="need">Lo que me ayudaría (opcional)</label><select id="need">${options(['Claridad','Descanso','Compañía','Espacio','Movimiento','Apoyo','Reconocer un avance','Continuar como estoy','No lo sé todavía'],state.need)}</select><label for="ownNeed">Otra necesidad (opcional)</label><input type="text" id="ownNeed" maxlength="160" value="${esc(state.ownNeed)}">`;
if(step===4)body=`<p>${state.moment==='Al cerrar'?'¿Qué te ayudó hoy o qué quieres reconocer de lo que hiciste?':'¿Qué paso pequeño y posible te acompañaría en lo que sigue?'}</p><p class="fine">Por ejemplo: pedir un ejemplo, tomar agua, organizar el primer paso o reconocer un avance.</p><label for="action">Mi acción o reconocimiento (opcional)</label><textarea id="action" maxlength="280">${esc(state.action)}</textarea><label class="check"><input id="save" type="checkbox" ${state.save?'checked':''}>Guardar esta pausa en este dispositivo.</label><p class="fine">Podrás consultarla y borrarla en «Mi historial». No se sincroniza con otros dispositivos ni con el check-in semanal.</p>`;
if(step===5)body=`<p>No necesitas cambiar lo que sientes para que esta pausa tenga valor.</p>${summary(state)}<p class="fine">${saved?'Pausa guardada en este navegador.':'Esta pausa no se ha guardado.'}</p><button id="restart">Hacer otra pausa</button>`;
app.innerHTML=`<div class="fine">${step<5?`Paso ${step+1} de 5`:'Pausa completada'}</div><div class="progress"><span style="width:${Math.min(100,(step+1)*20)}%"></span></div><section class="panel"><h2 tabindex="-1">${titles[step]}</h2>${body}${step<5?`<div class="actions">${step>0?'<button id="back" class="secondary">Anterior</button>':''}<button id="next">${step===4?'Terminar mi pausa':'Continuar'}</button></div>`:''}</section>`;
app.querySelectorAll('[data-moment]').forEach(b=>b.onclick=()=>{state.moment=b.dataset.moment;render(false)});
app.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{capture();state.group=Number(b.dataset.group);state.emotion='';state.ownEmotion='';render(false)});
app.querySelector('#unclear')?.addEventListener('click',()=>{state.group=null;state.emotion='No lo tengo claro';state.ownEmotion='';step++;render()});
app.querySelector('#back')?.addEventListener('click',()=>{capture();step--;render()});
app.querySelector('#next')?.addEventListener('click',()=>{capture();if(step===0&&!state.moment){notice.textContent='Elige el momento de tu pausa.';return}if(step===1&&!state.emotion&&!state.ownEmotion?.trim()){notice.textContent='Elige una palabra, escribe la tuya o selecciona «No lo tengo claro».';return}if(step===1&&state.emotion==='Otra emoción'&&!state.ownEmotion?.trim()){notice.textContent='Escribe tu palabra o elige «No lo tengo claro».';return}if(step===4&&state.save){try{const rows=readHistory();rows.unshift({...state,id:crypto.randomUUID(),date:new Date().toISOString()});localStorage.setItem(KEY,JSON.stringify(rows));saved=true;}catch{notice.textContent='No se pudo guardar la pausa. Revisa el almacenamiento de tu navegador o desmarca la casilla para terminar sin guardar.';return}}step++;render()});
app.querySelector('#restart')?.addEventListener('click',reset);
if(focus)app.querySelector('h2').focus();}
function capture(){['emotion','ownEmotion','reason','detail','need','ownNeed','action'].forEach(k=>{const e=app.querySelector('#'+k);if(e)state[k]=e.value});const save=app.querySelector('#save');if(save)state.save=save.checked;}
function summary(r){return '<dl>'+[['Momento',r.moment],['Emoción',r.ownEmotion?.trim()||r.emotion],['Posible razón',[r.reason,r.detail].filter(Boolean).join(' · ')],['Necesidad',r.ownNeed?.trim()||r.need],['Mi acción',r.action]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v||'Sin especificar')}</dd>`).join('')+'</dl>';}
function reset(){state={};step=0;saved=false;render();}
function history(){if(view==='flow')capture();view='history';notice.textContent='';let rows;try{rows=readHistory()}catch{app.innerHTML='<section class="panel"><h2 tabindex="-1">Mi historial</h2><p>No pudimos leer el historial guardado. Los datos no se han modificado.</p><button id="resume" class="secondary">Volver a mi pausa</button></section>';app.querySelector('#resume').onclick=()=>render();return;}app.innerHTML=`<section class="panel"><h2 tabindex="-1">Mi historial</h2><p class="fine">Solo las pausas que elegiste guardar en este navegador.</p>${rows.length?rows.map(r=>`<article class="entry"><h3>${esc(new Date(r.date).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'}))}</h3>${summary(r)}<button class="secondary" data-delete="${esc(r.id)}">Borrar esta pausa</button></article>`).join(''):'<p>Todavía no tienes pausas guardadas.</p>'}<div class="actions"><button id="resume" class="secondary">Volver a mi pausa</button>${rows.length?'<button id="clear" class="secondary">Borrar todo el historial</button>':''}</div></section>`;app.querySelector('#resume').onclick=()=>render();app.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('¿Borrar esta pausa guardada?'))remove(b.dataset.delete)});app.querySelector('#clear')?.addEventListener('click',()=>{if(confirm('¿Borrar todas las pausas de este navegador? Esta acción no se puede deshacer.'))remove()});app.querySelector('h2').focus();}
function remove(id){try{if(id)localStorage.setItem(KEY,JSON.stringify(readHistory().filter(r=>r.id!==id)));else localStorage.removeItem(KEY);history();notice.textContent='Historial actualizado.'}catch{notice.textContent='No se pudo borrar. Intenta de nuevo.'}}
document.querySelector('#history').onclick=history;render(false);
